### PR TITLE
Use $RANDOM from bash for random numbers

### PR DESCRIPTION
**Pull request by res0nance**
This allows MacOS to work without additional packages

### CODE REVIEW

**Comment by res0nance** [comment]
> Heya! Did you check for any shellcheck warnings & have you formatted your code with shfmt? Check the contributing guidelines for some info about this.

I only have access to my windows machine right now but hopefully I've managed to manually fix all the issues

**Comment by talwat** [comment]
I have heard some weird things about $RANDOM, so I can make some edits to make it only be used on macOS :)

**Comment by talwat** [comment]
I made a few additions, let me know if it all looks good to you and I can merge :)

**Comment by res0nance** [comment]
> I made a few additions, let me know if it all looks good to you and I can merge :)

I noticed a last bug, I'm happy with it now.

**Pull request merged**
