### PR TITLE
fix timings

### PR DESCRIPTION
**Pull request by acxz**
Went ahead and did thorough timing tests.
These should be the correct values that were achieved with the following script:
```bash
#!/usr/bin/env bash
runs=500

ps_time=0
pg_time=0
pc_time=0
for ((i = 0; i <= runs; i++)); do

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/github/acxz/pokeshell/pokeshell -s ns:espeon+m
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    ps_time=$( echo "scale=10 ; $ps_time + $runtime" | bc -l )
    echo "$ps_time"

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/github/talwat/pokeget/pokeget -small espeon
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    pg_time=$( echo "scale=10 ; $pg_time + $runtime" | bc -l )
    echo "$pg_time"

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/gitlab/phoneybadger/pokemon-colorscripts/pokemon-colorscripts.sh -n espeon
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    pc_time=$( echo "scale=10 ; $pc_time + $runtime" | bc -l )
    echo "$pc_time"

done
ps_avg_time=$( echo "scale=6 ; $ps_time / $runs" | bc )
pg_avg_time=$( echo "scale=6 ; $pg_time / $runs" | bc )
pc_avg_time=$( echo "scale=6 ; $pc_time / $runs" | bc )
echo "$ps_avg_time"
echo "$pg_avg_time"
echo "$pc_avg_time"

# Times
# runs | ps | pg | pc
# times | 0.094861 | 0.059900 | 0.011498
# ratios | 1x | 1.6x | 8x  |
# 5x b/t pg and pc
```

feel free to run it yourself on your machine

### CODE REVIEW

**Comment by talwat** [comment]
I will double check on my computer later.

**Comment by acxz** [comment]
So I went ahead and added caching and got some better results for pokeshell. Surprisingly, it is now actually faster than pokeget by a factor of 2.

**Comment by talwat** [comment]
Did you turn on pokeget's new caching feature as well?

**Comment by acxz** [comment]
o.O didn't realize I have just been using defaults, let me try

**Comment by acxz** [comment]
```
#!/usr/bin/env bash
runs=500

ps_time=0
pst_time=0
pg_time=0
pc_time=0
for ((i = 0; i < runs; i++)); do

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/github/acxz/pokeshell/pokeshell -s ns:espeon+m
    # /home/acxz/vcs/git/github/acxz/pokeshell/pokeshell -s ns:espeon+m
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    ps_time=$( echo "scale=10 ; $ps_time + $runtime" | bc -l )
    echo "$ps_time"

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/github/acxz/pokescript/pokescript espeon
    # /home/acxz/vcs/git/github/acxz/pokescript/pokescript espeon
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    pst_time=$( echo "scale=10 ; $pst_time + $runtime" | bc -l )
    echo "$pst_time"

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/github/talwat/pokeget/pokeget -small espeon
    # /home/acxz/vcs/git/github/talwat/pokeget/pokeget -small espeon
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    pg_time=$( echo "scale=10 ; $pg_time + $runtime" | bc -l )
    echo "$pg_time"

    start_time=$(date +%s.%N)
    2>/dev/null 1>&2 /home/acxz/vcs/git/gitlab/phoneybadger/pokemon-colorscripts/pokemon-colorscripts.py -n espeon
    # /home/acxz/vcs/git/gitlab/phoneybadger/pokemon-colorscripts/pokemon-colorscripts.py -n espeon
    end_time=$(date +%s.%N)
    runtime=$( echo "$end_time - $start_time" | bc -l )
    pc_time=$( echo "scale=10 ; $pc_time + $runtime" | bc -l )
    echo "$pc_time"

    echo " "

done

# Avg time
ps_avg_time=$( echo "scale=6 ; $ps_time / $runs" | bc )
pst_avg_time=$( echo "scale=6 ; $pst_time / $runs" | bc )
pg_avg_time=$( echo "scale=6 ; $pg_time / $runs" | bc )
pc_avg_time=$( echo "scale=6 ; $pc_time / $runs" | bc )

echo "Avg Times:"
echo "$ps_avg_time"
echo "$pst_avg_time"
echo "$pg_avg_time"
echo "$pc_avg_time"
echo " "

# Normalize against ps
ps_norm_time=$( echo "scale=6 ; $ps_avg_time / $ps_avg_time" | bc )
pst_norm_time=$( echo "scale=6 ; $ps_avg_time / $pst_avg_time" | bc )
pg_norm_time=$( echo "scale=6 ; $ps_avg_time / $pg_avg_time" | bc )
pc_norm_time=$( echo "scale=6 ; $ps_avg_time / $pc_avg_time" | bc )

echo "Norm Times:"
echo "$ps_norm_time"
echo "$pst_norm_time"
echo "$pg_norm_time"
echo "$pc_norm_time"
echo " "
```

Updated version of the script which also does the math for normalizing.

**Pull request merged**
