### PR TITLE
add pokeshell corrections

### PR DESCRIPTION
**Pull request by acxz**
Just some corrections.

I added a relative speed metric averaged over 10 runs of displaying the same pokemon to clarify the speed downside.
Once I test with pokemon-colorscripts I intend to add a speed row to the feature table at pokeshell's readme.

Also pokeshell has full compatibility and is tested with macOS.

Wanted to sneak in animations and multiple pokemon...

edit: if u can squash when merging that would be great.

### CODE REVIEW

**Comment by talwat** [comment]
It is? That's actually pretty neat. I didn't see it on the README, whoops.

**Comment by acxz** [comment]
> didn't see it on the README

didn't think it was worth mentioning haha

**Comment by acxz** [comment]
Also one more thing, I'm gonna be moving on to some other projects so I was wondering if you would be willing to be a collaborator for pokeshell?

Would you be okay if I transferred the repository over to you at some point?
Kinda have pokeget and pokeshell as sister projects?

**Comment by talwat** [comment]
I'm currently also working on a lot of things including school, so I'm not sure if I'm the best candidate to maintain your project. But I will try my best to contribute here and then :)

**Comment by acxz** [comment]
got it, no worries. Once I clean it up and get it to something that can resemble a version 1 release I'll prob add you as a collab to the project.

**Pull request merged**
