### PR TITLE
automaticaly figure name or id out

### PR DESCRIPTION
**Pull request by Vagahbond**
With this, the script figures out if it's given a name or an id, and then proceeds to curl the appropriated address.

This way, pokeget's use is more intuitive, and the configuration can be simplified :)﻿

### CODE REVIEW

**Comment by talwat** [comment]
This is really cool! Only one thing, can you remove it from the generated config file and USAGE.md?

**Comment by Vagahbond** [comment]
I'll do it later in the evening ;)

**Comment by justleoo** [comment]
hey @talwat hey, you can review the pull request yourself, remove whatever you want from it, and accept it

**Comment by talwat** [comment]
I can't do since i'm not at my computer.

**Comment by Vagahbond** [comment]
I was away so I could not do it neither ! 
Anyways cool little project you've got there, it's fun :)

**Comment by talwat** [comment]
Heya! I finished up removing it. Thanks a ton for your contribution! :)

**Pull request merged**
